/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   directives_array.cpp                               :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: htharrau <htharrau@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/06/22 14:19:50 by htharrau          #+#    #+#             */
/*   Updated: 2025/06/22 16:16:57 by htharrau         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ConfigParser.hpp"


const std::vector<Validity> validDirective = {

	{"events", {"main"}, true, 0},
	{"http", {"main"}, true, 0},
	{"mail", {"main"}, true, 0},
	{"stream", {"main"}, true, 0},
	{"types", {"http", "server", "location"}, true, 0},
	{"empty_gif", {"location"}, false, 0},
	{"worker_processes", {"main"}, false, 1},
	{"worker_rlimit_nofile", {"main"}, false, 1},
	{"pid", {"main"}, false, 1},
	{"error_log", {"main", "http", "server", "location"}, false, 2},
	{"daemon", {"main"}, false, 1},
	{"user", {"main"}, false, 2},
	{"worker_connections", {"events"}, false, 1},
	{"use", {"events"}, false, 1},
	{"multi_accept", {"events"}, false, 1},
	{"include", {"main", "http", "server", "location"}, false, SIZE_MAX},
	{"default_type", {"http"}, false, 1},
	{"sendfile", {"http"}, false, 1},
	{"tcp_nopush", {"http"}, false, 1},
	{"tcp_nodelay", {"http"}, false, 1},
	{"keepalive_timeout", {"http", "server"}, false, 2},
	{"client_max_body_size", {"http", "server", "location"}, false, 1},
	{"gzip", {"http"}, false, 1},
	{"gzip_disable", {"http"}, false, SIZE_MAX},
	{"gzip_vary", {"http"}, false, 1},
	{"gzip_proxied", {"http"}, false, SIZE_MAX},
	{"gzip_comp_level", {"http"}, false, 1},
	{"gzip_types", {"http"}, false, SIZE_MAX},
	{"server_tokens", {"http"}, false, 1},
	{"server", {"http"}, true, 0},
	{"limit_conn_zone", {"http"}, false, 2},
	{"limit_conn", {"http", "server", "location"}, false, 2},
	{"limit_req_zone", {"http"}, false, 3},
	{"limit_req", {"http", "server", "location"}, false, 2},
	{"map", {"http"}, true, 2},
	{"geo", {"http"}, true, 1},
	{"upstream", {"http"}, true, 1},
	{"listen", {"server"}, false, SIZE_MAX},
	{"server_name", {"server"}, false, SIZE_MAX},
	{"root", {"http", "server", "location"}, false, 1},
	{"index", {"http", "server", "location"}, false, SIZE_MAX},
	{"autoindex", {"http", "server", "location"}, false, 1},
	{"error_page", {"http", "server", "location"}, false, SIZE_MAX},
	{"rewrite_log", {"server", "location"}, false, 1},
	{"location", {"server"}, true, 2},
	{"if", {"location", "server"}, true, 1},
	{"limit_except", {"location"}, true, SIZE_MAX},
	{"try_files", {"location"}, false, SIZE_MAX},
	{"return", {"location", "server"}, false, 2},
	{"proxy_pass", {"location"}, false, 1},
	{"fastcgi_pass", {"location"}, false, 1},
	{"fastcgi_param", {"location"}, false, 2},
	{"proxy_set_header", {"location"}, false, 2},
	{"charset_map", {"http"}, true, 2},
	{"auth_http", {"mail"}, true, 1},
	{"access_log", {"http", "server", "location"}, false, 2},
	{"add_header", {"http", "server", "location"}, false, SIZE_MAX},
	{"alias", {"location"}, false, 1},
	{"allow", {"http", "server", "location"}, false, 1},
	{"deny", {"http", "server", "location"}, false, 1},
	{"client_body_buffer_size", {"http", "server", "location"}, false, 1},
	{"client_body_timeout", {"http", "server", "location"}, false, 1},
	{"client_header_buffer_size", {"http", "server", "location"}, false, 1},
	{"client_header_timeout", {"http", "server", "location"}, false, 1},
	{"expires", {"http", "server", "location"}, false, 2},
	{"gzip_buffers", {"http"}, false, 2},
	{"gzip_min_length", {"http"}, false, 1},
	{"limit_rate", {"http", "server", "location"}, false, 1},
	{"log_format", {"http"}, false, SIZE_MAX},
	{"open_file_cache", {"http", "server", "location"}, false, 1},
	{"proxy_buffering", {"http", "server", "location"}, false, 1},
	{"proxy_cache", {"http", "server", "location"}, false, 1},
	{"proxy_cache_path", {"http"}, false, SIZE_MAX},
	{"rewrite", {"server", "location"}, false, SIZE_MAX},
	{"ssl_certificate", {"http", "server"}, false, 1},
	{"absolute_redirect", {"http", "server", "location"}, false, 1},
	{"aio", {"http", "server", "location"}, false, 1},
	{"auth_basic", {"http", "server", "location"}, false, 1},
	{"auth_basic_user_file", {"http", "server", "location"}, false, 1},
	{"charset", {"http", "server", "location"}, false, 1},
	{"charset_types", {"http", "server", "location"}, false, SIZE_MAX},
	{"chunked_transfer_encoding", {"http", "server", "location"}, false, 1},
	{"client_body_in_file_only", {"http", "server", "location"}, false, 1},
	{"client_body_in_single_buffer", {"http", "server", "location"}, false, 1},
	{"client_body_temp_path", {"http", "server", "location"}, false, 4},
	{"directio", {"http", "server", "location"}, false, 2},
	{"directio_alignment", {"http", "server", "location"}, false, 1},
	{"disable_symlinks", {"http", "server", "location"}, false, 2},
	{"fastcgi_buffer_size", {"http", "server", "location"}, false, 1},
	{"fastcgi_buffers", {"http", "server", "location"}, false, 2},
	{"fastcgi_cache", {"http", "server", "location"}, false, 1},
	{"fastcgi_cache_key", {"http", "server", "location"}, false, SIZE_MAX},
	{"fastcgi_cache_path", {"http"}, false, SIZE_MAX},
	{"fastcgi_cache_use_stale", {"http", "server", "location"}, false, SIZE_MAX},
	{"fastcgi_index", {"http", "server", "location"}, false, 1},
	{"fastcgi_read_timeout", {"http", "server", "location"}, false, 1},
	{"gzip_http_version", {"http"}, false, 1},
	{"gzip_static", {"http", "server", "location"}, false, 1}

};


